# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a132d6481cd77917c090abc8c29236a78f581f8ae6c4b8b069ac61fc53646f1e8074dee1c6e32de16a6bdf220183123138afb187b84a855e5771c229c131a70b

test:
  secret_key_base: 1b87c8636b16a23eb5defb8365d70290d8841069280b900db8920d1526dd233d0888cdc01cdabec0f5142107f4f478533932532eb443c73147f703b4f6a4b9cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
